version: '3.8'
services:
  node_db:
    image: postgres:12
    container_name: node_db
    ports:
      - "5432:5432"
    volumes:
      - node_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=devhola
      - POSTGRES_DB=node_live_db_test
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  node_app:
    build: .
    container_name: node_app
    image: devhola/node_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      PG_USER: devhola
      PG_PASSWORD: 12345678
      PG_HOST: node_db
      PG_DB: node_live_db_test
    depends_on:
      - node_db
volumes:
  node_db_data: {}

